/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatp2p;

import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Miky
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        
        initComponents();
        setResizable(false); //non permetto di modificare le dimensioni della finestra
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtMittente = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        BtnConn = new javax.swing.JButton();
        BtnMess = new javax.swing.JButton();
        BtnDisc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtDest = new javax.swing.JTextArea();
        TxtNomeMitt = new javax.swing.JTextField();
        TxtNomeDest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Destinatario:");

        TxtMittente.setColumns(20);
        TxtMittente.setLineWrap(true);
        TxtMittente.setRows(5);
        jScrollPane2.setViewportView(TxtMittente);

        jLabel2.setText("Mittente:");

        BtnConn.setText("CONNESSIONE");
        BtnConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConnActionPerformed(evt);
            }
        });

        BtnMess.setText("INVIA MESSAGGIO");
        BtnMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMessActionPerformed(evt);
            }
        });

        BtnDisc.setText("DISCONNESSIONE");

        TxtDest.setColumns(20);
        TxtDest.setLineWrap(true);
        TxtDest.setRows(5);
        jScrollPane3.setViewportView(TxtDest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNomeMitt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNomeDest, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BtnConn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDisc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(BtnMess, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNomeMitt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNomeDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConn)
                    .addComponent(BtnDisc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnMess)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void BtnConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConnActionPerformed

        DatiCondivisi dati = new DatiCondivisi();
        if(TxtNomeMitt.getText().equals("")) //se non ha inserito il suo nome
            JOptionPane.showMessageDialog(null, "Devi prima inserire il tuo nome", "Errore", 0); //pop-up
        else{
            dati.AddDaInviare("c;" + TxtNomeMitt.getText());
        }     
    }//GEN-LAST:event_BtnConnActionPerformed

    //metodo per accettare o rifiutare la connessione
    public void MessConnessione(DatiCondivisi d,String nomeMitt) throws UnknownHostException
    {
        String risp  = "";
        ThreadClient c = new ThreadClient();
        
        int risposta = JOptionPane.showConfirmDialog(null, "Accettare connessione da " + nomeMitt + "?", "Richiesta connessione", JOptionPane.YES_NO_OPTION );
        if (risposta == JOptionPane.YES_OPTION) {
            TxtNomeDest.setText(nomeMitt); //!!! non lo inserisce
            String nomeUtente = "";
            while(nomeUtente.equals(""))
            {
                nomeUtente = JOptionPane.showInputDialog("inserisci il tuo nome");
            }
            TxtNomeMitt.setText(nomeUtente); //!!! non lo inserisce
            d.setConnesso(true); //connesso
            d.setInvia("y;" + nomeUtente);
        }
        else {
            d.setConnesso(false); //non connesso
            d.setInvia("n");
        }
    }
    
    public void OkConn(String NomeDest) //metodo connessione accettata
    {
        JOptionPane.showMessageDialog(null, "richiesta di connessione accettata da " + NomeDest, "Ok Connessione", 1); //pop-up
        TxtNomeDest.setText(NomeDest); //!!! non lo inserisce
    }
    
    public void NoConn() {
        JOptionPane.showMessageDialog(null, "connessione rifiutata", "no Connessione", 0); //pop-up
    }

    private void BtnMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMessActionPerformed
        /*if(DatiCondivisi.isConnesso() == true)
        {
            ThreadClient c = new ThreadClient();
            try {
                c.InviaPacchetto("m;" + TxtMittente.getText()); //invio il pacchetto con il mio nome
            } catch (UnknownHostException ex) {
                Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Effettuare la connessione prima di inviare un messaggio");
    }//GEN-LAST:event_BtnMessActionPerformed

    public void VisMess(String mes) { //visualizza il messaggio ricevuto
        System.out.println(mes);*/
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
                DatiCondivisi dati = new DatiCondivisi();
                ThreadClient client;
                try {
                    client = new ThreadClient(dati);
                    client.start();
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                ThreadServer server;
                try {
                    server = new ThreadServer(dati);
                    server.start();
                } catch (SocketException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }   
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConn;
    private javax.swing.JButton BtnDisc;
    private javax.swing.JButton BtnMess;
    private javax.swing.JTextArea TxtDest;
    private javax.swing.JTextArea TxtMittente;
    private javax.swing.JTextField TxtNomeDest;
    private javax.swing.JTextField TxtNomeMitt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    


}
